import { Inter } from "next/font/google";
import { Cairo } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import "./globals.css";
import { icons } from "lucide-react";

const inter = Inter({
  subsets: ["latin"],
});

const cairo = Cairo({
  subsets: ["arabic"],
});

export const metadata = {
  title: "Rawdatee Platform",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default async function LocaleLayout({ children, params }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <head>
        {/* JSON-LD for Google Logo */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              url: "https://rawdatee.com",
              logo: "https://rawdatee.com/logo.png",
            }),
          }}
        />
      </head>

      <body className={locale === "ar" ? cairo.className : inter.className}>
        <NextIntlClientProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
